baseURL = "https://rohank.dev/"
languageCode = "en-us"
title = "Rohan's Blog"
theme="archie"

copyright = "© Rohan"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="dark"
	featherIconsCDN=true
	subtitle = "Recent Posts"

# Socials

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/rk2810"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/rohan-khurana-340b1b147/"

[[params.social]]
name = "Telegram"
icon = "message-circle"
url = "https://t.me/PulsatingQuasar"

# Sections

[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects/projects"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4